# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Layout/IndentationConsistency:
  Enabled: true

Metrics/ClassLength:
  Max: 1500

Layout/ParameterAlignment:
  Enabled: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: true
